"""Sandbox M2 RL curriculum scaffold."""

from .curriculum import (
    CalibratedReward,
    DEFAULT_JUDGE_DECISION_THRESHOLD,
    DEFAULT_JUDGE_DISPATCH_BLOCKERS,
    DEFAULT_RL_CURRICULUM_BLOCKERS,
    CurriculumSamplingPlan,
    EnvGapConfig,
    EnvGapEstimate,
    EnvJudgeRoutingPolicy,
    JudgeDispatchRecord,
    RewardCalibrationSummary,
    SamplingAllocation,
    build_dynamic_sampling_plan,
    build_default_env_judge_routing_policies,
    build_reward_calibration_summaries,
    calibrate_rollout_rewards,
    calibrate_trace_reward,
    dispatch_judge_ensembles_for_rollouts,
    estimate_env_gaps,
    format_curriculum_plan,
    judge_ensemble_result_to_rollout_metrics,
    judge_response_to_rollout_metrics,
    rollout_trace_to_judge_request,
)

__all__ = [
    "CalibratedReward",
    "DEFAULT_JUDGE_DECISION_THRESHOLD",
    "DEFAULT_JUDGE_DISPATCH_BLOCKERS",
    "DEFAULT_RL_CURRICULUM_BLOCKERS",
    "CurriculumSamplingPlan",
    "EnvGapConfig",
    "EnvGapEstimate",
    "EnvJudgeRoutingPolicy",
    "JudgeDispatchRecord",
    "RewardCalibrationSummary",
    "SamplingAllocation",
    "build_dynamic_sampling_plan",
    "build_default_env_judge_routing_policies",
    "build_reward_calibration_summaries",
    "calibrate_rollout_rewards",
    "calibrate_trace_reward",
    "dispatch_judge_ensembles_for_rollouts",
    "estimate_env_gaps",
    "format_curriculum_plan",
    "judge_ensemble_result_to_rollout_metrics",
    "judge_response_to_rollout_metrics",
    "rollout_trace_to_judge_request",
]
